### ISSUE TITLE
显示验证不成功

### ISSUE THREAD

**Issue by hit-wpc** [Taoduhui/Stm32CubeAuto#3]
选择publish文件下的set up.exe，显示发行者未知，安装失败。系统是windows11，请问是什么问题呢

**Comment by Taoduhui** [comment]
你可以直接下载release版本，解压后打开Stm32CubeAuto,exe即可
链接：[https://github.com/Taoduhui/Stm32CubeAuto/releases/latest](https://github.com/Taoduhui/Stm32CubeAuto/releases/latest)

**Comment by Taoduhui** [comment]
你可以直接下载release版本，解压后打开Stm32CubeAuto,exe即可
链接：[https://github.com/Taoduhui/Stm32CubeAuto/releases/latest](https://github.com/Taoduhui/Stm32CubeAuto/releases/latest)
